### ISSUE TITLE
Brak podpisywania żądań w APIv2

### ISSUE THREAD

**Issue by rnickson** [p1c2u/wykop-sdk#17]
To się powinno przydać:
https://github.com/feelfreelinux/WykopMobilny/blob/master/app/src/main/kotlin/io/github/feelfreelinux/wykopmobilny/api/ApiSignInterceptor.kt

**Comment by p1c2u** [comment]
@rnickson dzieki na pewno sie przyda

**Comment by p1c2u** [comment]
@rnickson przyjrzalem sie dokladnie i wyglada tak samo jak aktualnie zaimplementowany
https://github.com/p1c2u/wykop-sdk/blob/master/wykop/api/clients.py#L76
